set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER x86_64-elf-gcc)
set(CMAKE_C_TEST_COMPILER /usr/bin/gcc)
set(CMAKE_ASM_COMPILER x86_64-elf-gcc)
set(FLAGS_COMMON_ARCH "-m64 -mno-red-zone -march=nehalem")
