SET(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86-64)
set(CMAKE_C_COMPILER x86_64-elf-gcc)
set(FLAGS_COMMON_ARCH -m64 -g -std=c99 -mno-red-zone)
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "/usr/local/lib/gcc/x86_64-elf/6.3.0/crti.o /usr/local/lib/gcc/x86_64-elf/6.3.0/crti.o -lc")
